import {
  City,
  Day,
  Entry,
  Supercharger,
  PackingItem,
  BudgetCat,
} from './types';

// Trip metadata
export const TRIP_META = {
  title: 'Oslo → Stavanger, the long way home',
  subtitle: 'A 19-day European loop · Tesla Model Y Juniper',
  budget: 6800,
  currency: 'EUR',
  start: '2026-06-16',
  end: '2026-07-03',
};

// Cities on the route
export const cities: City[] = [
  { id: 'oslo', name: 'Oslo', country: 'Norway', flag: '🇳🇴', lat: 59.91, lng: 10.75, label: 'Start' },
  { id: 'kiel', name: 'Kiel', country: 'Germany', flag: '🇩🇪', lat: 54.32, lng: 10.13, label: 'Ferry arr.' },
  { id: 'bremen', name: 'Bremen', country: 'Germany', flag: '🇩🇪', lat: 53.08, lng: 8.8, nights: 1 },
  { id: 'brus', name: 'Brussels', country: 'Belgium', flag: '🇧🇪', lat: 50.85, lng: 4.35, nights: 1 },
  { id: 'paris', name: 'Paris', country: 'France', flag: '🇫🇷', lat: 48.85, lng: 2.35, nights: 4 },
  { id: 'lyon', name: 'Lyon', country: 'France', flag: '🇫🇷', lat: 45.76, lng: 4.83, nights: 2 },
  { id: 'turin', name: 'Turin', country: 'Italy', flag: '🇮🇹', lat: 45.07, lng: 7.69, nights: 2 },
  { id: 'lugano', name: 'Lugano', country: 'Switzerland', flag: '🇨🇭', lat: 46.0, lng: 8.96, nights: 1 },
  { id: 'zur', name: 'Zürich', country: 'Switzerland', flag: '🇨🇭', lat: 47.37, lng: 8.54, nights: 1 },
  { id: 'stutt', name: 'Stuttgart', country: 'Germany', flag: '🇩🇪', lat: 48.78, lng: 9.18, nights: 1 },
  { id: 'hamb', name: 'Hamburg', country: 'Germany', flag: '🇩🇪', lat: 53.55, lng: 10.0, nights: 1 },
  { id: 'cph', name: 'Copenhagen', country: 'Denmark', flag: '🇩🇰', lat: 55.68, lng: 12.57, nights: 1 },
  { id: 'hir', name: 'Hirtshals', country: 'Denmark', flag: '🇩🇰', lat: 57.59, lng: 9.96, label: 'Ferry dep.' },
  { id: 'krs', name: 'Kristiansand', country: 'Norway', flag: '🇳🇴', lat: 58.15, lng: 7.99, label: 'Ferry arr.' },
  { id: 'svg', name: 'Stavanger', country: 'Norway', flag: '🇳🇴', lat: 58.97, lng: 5.73, label: 'Home' },
];

// Itinerary days
export const days: Day[] = [
  { d: 1, date: '2026-06-16', city: 'oslo', title: 'Roll-on Oslo', note: 'Last-minute packing. Charge to 100% at home.' },
  { d: 2, date: '2026-06-17', city: 'kiel', title: 'Land in Kiel', note: 'Ferry docks 10:00. Easy day to Bremen.' },
  { d: 3, date: '2026-06-18', city: 'bremen', title: 'Bremen → Brussels', note: '~450 km. One charge at Münster.' },
  { d: 4, date: '2026-06-19', city: 'brus', title: 'Brussels → Paris', note: '~310 km. Charge at Senlis before city traffic.' },
  { d: 5, date: '2026-06-20', city: 'paris', title: 'Paris arrival', note: 'Walk Île de la Cité. Early dinner.' },
  { d: 6, date: '2026-06-21', city: 'paris', title: 'Disneyland Paris', note: 'RER A from Châtelet, ~40 min. Bring rain jacket.' },
  { d: 7, date: '2026-06-22', city: 'paris', title: 'Louvre + Marais', note: 'Timed entry 09:30. Reserve restaurant.' },
  { d: 8, date: '2026-06-23', city: 'paris', title: 'Paris → Lyon', note: '~465 km. Charge Beaune-Tailly, the OG Tesla SC.' },
  { d: 9, date: '2026-06-24', city: 'lyon', title: 'Vieux Lyon', note: 'Bouchon dinner. Funicular up to Fourvière.' },
  { d: 10, date: '2026-06-25', city: 'lyon', title: 'Lyon → Turin', note: 'Through Mont Blanc tunnel. Stunning.' },
  { d: 11, date: '2026-06-26', city: 'turin', title: 'Turin / Milan', note: 'Day trip to Milan by train (50 min).' },
  { d: 12, date: '2026-06-27', city: 'turin', title: 'Turin → Lugano', note: 'Scenic alpine pass. Don\'t speed.' },
  { d: 13, date: '2026-06-28', city: 'lugano', title: 'Lugano → Zürich', note: 'Cross via Gotthard. Swim if it\'s hot.' },
  { d: 14, date: '2026-06-29', city: 'zur', title: 'Zürich → Stuttgart', note: '~220 km. Mercedes Museum if there\'s time.' },
  { d: 15, date: '2026-06-30', city: 'stutt', title: 'Stuttgart → Hamburg', note: 'Long day. ~650 km. Autobahn = fast charges.' },
  { d: 16, date: '2026-07-01', city: 'hamb', title: 'Hamburg → Copenhagen', note: 'Cross the Fehmarn ferry. Reserve in advance.' },
  { d: 17, date: '2026-07-02', city: 'cph', title: 'Copenhagen → Hirtshals', note: '~470 km. Catch the night ferry to Kristiansand.' },
  { d: 18, date: '2026-07-03', city: 'krs', title: 'Kristiansand → Stavanger 🏡', note: 'Final stretch. Home for dinner.' },
];

// Bookings / entries
export const initialEntries: Entry[] = [
  {
    id: 'e1',
    kind: 'ferry',
    title: 'Color Line — Oslo → Kiel',
    vendor: 'Color Line',
    ref: 'CL-7F2KQ',
    start: '2026-06-16T14:00',
    end: '2026-06-17T10:00',
    city: 'oslo',
    where: 'Hjortneskaia, 0250 Oslo',
    pax: '2 adults + 1 vehicle (cabin 8042, outside view)',
    price: 412,
    currency: 'EUR',
    source: 'Booking confirmation, colorline.no',
    raw: 'Color Line MS Color Magic\nDeparture: 16 June 2026, 14:00 — Hjortneskaia, Oslo\nArrival: 17 June 2026, 10:00 — Norwegenkai, Kiel\nBooking ref: CL-7F2KQ\nCabin 8042 (outside, deck 8) · Vehicle: Tesla Model Y, EL 12345\nTotal: 4,120 NOK',
  },
  {
    id: 'e2',
    kind: 'hotel',
    title: 'Atlantic Hotel Universum',
    vendor: 'Booking.com',
    ref: '4471.998.221',
    start: '2026-06-17T15:00',
    end: '2026-06-18T11:00',
    city: 'bremen',
    where: 'Wiener Straße 4, 28359 Bremen',
    pax: 'Double room, free parking, Tesla destination charger on-site',
    price: 168,
    currency: 'EUR',
    source: 'Booking.com email',
    raw: 'Your booking is confirmed!\nAtlantic Hotel Universum · Bremen\nCheck-in: Wed, Jun 17 (from 15:00)\nCheck-out: Thu, Jun 18 (until 11:00)\nDouble Room with Parking · €168.00 total · Confirmation 4471.998.221',
  },
  {
    id: 'e3',
    kind: 'hotel',
    title: 'Hotel Le Berger',
    vendor: 'Booking.com',
    ref: '5588.221.044',
    start: '2026-06-18T16:00',
    end: '2026-06-19T11:00',
    city: 'brus',
    where: 'Rue du Berger 24, 1050 Ixelles, Brussels',
    pax: 'Deluxe room — quirky 1930s art deco',
    price: 142,
    currency: 'EUR',
    source: 'Booking.com',
  },
  {
    id: 'e4',
    kind: 'hotel',
    title: 'Hôtel des Grands Boulevards',
    vendor: 'Hotel email',
    ref: 'HGB-26-4421',
    start: '2026-06-19T15:00',
    end: '2026-06-23T11:00',
    city: 'paris',
    where: '17 Boulevard Poissonnière, 75002 Paris',
    pax: 'Junior suite, 4 nights · valet parking (€45/night)',
    price: 1240,
    currency: 'EUR',
    source: 'Direct hotel reservation',
    raw: 'Bonjour Magnus,\n\nNous avons le plaisir de confirmer votre réservation:\nArrivée: vendredi 19 juin 2026 à partir de 15h00\nDépart: mardi 23 juin 2026 avant 11h00\nChambre: Junior Suite (4 nuits)\nVoiturier disponible · 45€/nuit\nTotal: 1 240,00 €',
  },
  {
    id: 'e5',
    kind: 'activity',
    title: 'Disneyland Paris — 1 Day / 2 Parks',
    vendor: 'Disneyland Paris',
    ref: 'DLP-9921-44',
    start: '2026-06-21T09:30',
    end: '2026-06-21T22:00',
    city: 'paris',
    where: 'Marne-la-Vallée, RER A',
    pax: '2 adults · Premier Access included',
    price: 268,
    currency: 'EUR',
    source: 'PDF ticket',
  },
  {
    id: 'e6',
    kind: 'dining',
    title: 'Le Comptoir de la Gastronomie',
    vendor: 'TheFork',
    ref: 'TF-22018',
    start: '2026-06-22T20:00',
    end: '2026-06-22T22:30',
    city: 'paris',
    where: '34 Rue Montmartre, 75001 Paris',
    pax: 'Table for 2 · classic French bistro',
    price: 0,
    currency: 'EUR',
    source: 'TheFork email',
  },
  {
    id: 'e7',
    kind: 'hotel',
    title: 'Cour des Loges',
    vendor: 'Booking.com',
    ref: '7702.118.553',
    start: '2026-06-23T16:00',
    end: '2026-06-25T11:00',
    city: 'lyon',
    where: '6 Rue du Bœuf, 69005 Lyon (Vieux Lyon)',
    pax: 'Renaissance courtyard · 2 nights',
    price: 520,
    currency: 'EUR',
  },
  {
    id: 'e8',
    kind: 'airbnb',
    title: 'Loft in Quadrilatero Romano',
    vendor: 'Airbnb',
    ref: 'HMABCD1234',
    start: '2026-06-25T17:00',
    end: '2026-06-27T10:00',
    city: 'turin',
    where: 'Via San Domenico, 10122 Torino',
    pax: 'Whole place · 1BR · host: Giulia',
    price: 312,
    currency: 'EUR',
    source: 'Airbnb reservation',
    raw: 'Reservation confirmed · HMABCD1234\nHost: Giulia (Superhost)\nCheck-in: Jun 25, after 17:00\nCheck-out: Jun 27, before 10:00\nGuests: 2 · Entire loft · €312 total\nSelf check-in with smart lock — code arrives day-of.',
  },
  {
    id: 'e9',
    kind: 'hotel',
    title: 'Splendide Royal Lugano',
    vendor: 'Booking.com',
    ref: '9911.443.020',
    start: '2026-06-27T16:00',
    end: '2026-06-28T11:00',
    city: 'lugano',
    where: 'Riva Antonio Caccia 7, 6900 Lugano',
    pax: 'Lake-view double, half-board',
    price: 410,
    currency: 'EUR',
  },
  {
    id: 'e10',
    kind: 'hotel',
    title: 'Hotel Marktgasse',
    vendor: 'Booking.com',
    ref: '3344.901.118',
    start: '2026-06-28T15:00',
    end: '2026-06-29T11:00',
    city: 'zur',
    where: 'Marktgasse 17, 8001 Zürich',
    pax: 'Old-town boutique · 1 night',
    price: 295,
    currency: 'CHF',
  },
  {
    id: 'e11',
    kind: 'hotel',
    title: 'Der Zauberlehrling',
    vendor: 'Hotel email',
    ref: 'ZL-2641',
    start: '2026-06-29T15:00',
    end: '2026-06-30T11:00',
    city: 'stutt',
    where: 'Rosenstraße 38, 70182 Stuttgart',
    pax: 'Themed room: \'Reise um die Welt\'',
    price: 220,
    currency: 'EUR',
  },
  {
    id: 'e12',
    kind: 'hotel',
    title: '25hours Hotel HafenCity',
    vendor: 'Booking.com',
    ref: '8801.226.119',
    start: '2026-06-30T16:00',
    end: '2026-07-01T11:00',
    city: 'hamb',
    where: 'Überseeallee 5, 20457 Hamburg',
    pax: 'Maritime-themed double',
    price: 188,
    currency: 'EUR',
  },
  {
    id: 'e13',
    kind: 'hotel',
    title: 'Hotel Skt. Petri',
    vendor: 'Booking.com',
    ref: '4458.776.339',
    start: '2026-07-01T16:00',
    end: '2026-07-02T11:00',
    city: 'cph',
    where: 'Krystalgade 22, 1172 København',
    pax: 'Design hotel, walkable to everything',
    price: 245,
    currency: 'EUR',
  },
  {
    id: 'e14',
    kind: 'ferry',
    title: 'Fjord Line — Hirtshals → Kristiansand',
    vendor: 'Fjord Line',
    ref: 'FL-88AA2',
    start: '2026-07-02T20:00',
    end: '2026-07-03T02:15',
    city: 'hir',
    where: 'Hirtshals Færgeterminal',
    pax: '2 adults + Tesla · inside cabin',
    price: 268,
    currency: 'EUR',
    raw: 'Fjord Line · MS Stavangerfjord\nDeparture: 2 July 2026, 20:00 — Hirtshals\nArrival: 3 July 2026, 02:15 — Kristiansand\nReference: FL-88AA2 · Inside cabin 4112\nVehicle: Tesla Model Y',
  },
  {
    id: 'e15',
    kind: 'note',
    title: 'Stay with Mum — Stavanger',
    start: '2026-07-03T12:00',
    end: '2026-07-03T23:59',
    city: 'svg',
    where: 'Mossiges gate, Stavanger',
    pax: 'Home! Sleep for a week.',
  },
];

// Tesla Superchargers planned along the way
export const chargers: Supercharger[] = [
  { name: 'Hamburg-Stillhorn', lat: 53.49, lng: 10.03, stalls: 16, kw: 250 },
  { name: 'Münster', lat: 51.96, lng: 7.63, stalls: 12, kw: 250 },
  { name: 'Senlis', lat: 49.2, lng: 2.58, stalls: 20, kw: 250 },
  { name: 'Beaune-Tailly', lat: 47.02, lng: 4.84, stalls: 28, kw: 250 },
  { name: 'Chambéry', lat: 45.57, lng: 5.92, stalls: 10, kw: 250 },
  { name: 'Aosta', lat: 45.74, lng: 7.32, stalls: 8, kw: 150 },
  { name: 'Affoltern am Albis', lat: 47.28, lng: 8.45, stalls: 12, kw: 250 },
  { name: 'Wendlingen', lat: 48.67, lng: 9.36, stalls: 16, kw: 250 },
  { name: 'Padborg', lat: 54.82, lng: 9.36, stalls: 12, kw: 250 },
  { name: 'Aalborg V', lat: 57.05, lng: 9.83, stalls: 8, kw: 250 },
  { name: 'Lyngdal', lat: 58.14, lng: 7.07, stalls: 6, kw: 150 },
];

// Packing items (flattened with sequential IDs)
export const initialPackingItems: PackingItem[] = [
  { id: 'p1', label: 'CCS2 → Type 2 charge adapter', group: 'Car', packed: true },
  { id: 'p2', label: 'Schuko + CEE 16A granny cable', group: 'Car', packed: true },
  { id: 'p3', label: 'Window sun shades (kids\' nap)', group: 'Car', packed: false },
  { id: 'p4', label: 'Tesla key cards × 2', group: 'Car', packed: true },
  { id: 'p5', label: 'Microfibre cloth + glass cleaner', group: 'Car', packed: false },
  { id: 'p6', label: 'Cooler bag + ice packs', group: 'Car', packed: false },
  { id: 'p7', label: 'Passports × 2', group: 'Documents', packed: true },
  { id: 'p8', label: 'Green card (insurance, EU)', group: 'Documents', packed: true },
  { id: 'p9', label: 'V5 vehicle registration', group: 'Documents', packed: true },
  { id: 'p10', label: 'Color Line ferry tickets', group: 'Documents', packed: true },
  { id: 'p11', label: 'Fjord Line ferry tickets', group: 'Documents', packed: false },
  { id: 'p12', label: 'Disneyland tickets (printed backup)', group: 'Documents', packed: false },
  { id: 'p13', label: 'International driving permit', group: 'Documents', packed: false },
  { id: 'p14', label: 'Rain jackets × 2', group: 'Clothes', packed: false },
  { id: 'p15', label: 'Swimwear (Lugano lake)', group: 'Clothes', packed: false },
  { id: 'p16', label: 'One nice outfit for Paris dinner', group: 'Clothes', packed: false },
  { id: 'p17', label: 'Sturdy walking shoes', group: 'Clothes', packed: false },
  { id: 'p18', label: 'Sunglasses', group: 'Clothes', packed: true },
  { id: 'p19', label: 'Phone chargers × 3', group: 'Tech', packed: false },
  { id: 'p20', label: 'USB-C → Lightning cable', group: 'Tech', packed: false },
  { id: 'p21', label: 'GoPro + spare batteries', group: 'Tech', packed: false },
  { id: 'p22', label: 'Universal travel adapter', group: 'Tech', packed: true },
  { id: 'p23', label: 'Offline maps downloaded', group: 'Tech', packed: false },
];

// Budget categories
export const budgetCats: BudgetCat[] = [
  { id: 'stay', label: 'Stays', planned: 3450, color: '--accent' },
  { id: 'travel', label: 'Ferries & tolls', planned: 980, color: '--sage' },
  { id: 'charge', label: 'Charging', planned: 280, color: '--sky' },
  { id: 'food', label: 'Food & wine', planned: 1400, color: '--mustard' },
  { id: 'do', label: 'Activities', planned: 690, color: '--plum' },
];
